### ISSUE TITLE
Bullets are bugged

### ISSUE THREAD

**Issue by laxa** [DDRace/teeworlds#104]
Since 0.6.1, bullets are bugged, they are going out of their way, and going to fast, same for explosion bullet !

**Comment by heinrich5991** [comment]
again? -.-

**Comment by laxa** [comment]
Yes :(.

**Comment by Shahan** [comment]
i hate ddrace on 0.6.1

**Comment by laxa** [comment]
Ok, I found out where this is coming from.
If server start with sv_tune_reset 0, then bullets will be bugged. If server start with sv_tune_reset 1, then bullet won't be bugged.
So changing sv_tune_reset value and changemap won't unbug bullet. So I guess default of sv_tune_reset should be set to 1 !

**Comment by JulianAssange** [comment]
^but that doesnt  make sense, seeing as on server start all tunes get reset..

**Comment by laxa** [comment]
That doesn't make sense but that's it...
Maybe Greyfox forgot something in this commit :
https://github.com/GreYFoX/teeworlds/commit/9f16db09692e31311c2b6293135001730f91291a

**Comment by GreYFoX** [comment]
this is fixed, and if it's not then the person using the bullets modified the shotgun_curvature tune

**Comment by GreYFoX** [comment]
@Laxa please if you find an issue you can't verify or think it's done, close it and mention @greyfox so that i would take a look later
