### ISSUE TITLE
Time is in decimal and wrong on race mod

### ISSUE THREAD

**Issue by laxa** [DDRace/teeworlds#105]
With DDRace client, best time of server is wrong, and personnal time is in decimal instead of seconds, and aswell as in DDRace, check entitie don't work correctly, or at least you don't get your check time on the screen !

**Comment by GreYFoX** [comment]
I wanted to make DDRace compatible with Race servers but for some reason @btd didn't agree at the time
if he doesn't clarify why soon, i will edit DDRace to be compatible with racemod or i will do a pul lrequest and edit DDRace to standardize them both to something better

**Comment by btd** [comment]
I agree with making it supports both.
