### ISSUE TITLE
Solo entitie not shown with proper graphic

### ISSUE THREAD

**Issue by laxa** [DDRace/teeworlds#109]
"Bug" is on client side, when you activate cl_show_entitie 1, solo entities (in and out) are not shown with proper graphic, only number is given.

**Comment by GreYFoX** [comment]
@Fisico please edit the entities_clear.png to show a combination of all tiles on entities.png files like tele,speedup,swithch...etc

**Comment by Fisico** [comment]
@greyfox 
sorry i lost all my rawfiles of the ddrace_entities... :(

**Comment by GreYFoX** [comment]
@Fisico np, take your time, there is nothing critical about this issue

**Comment by GreYFoX** [comment]
i did it and forgot to close
