### ISSUE TITLE
emptional tees never off

### ISSUE THREAD

**Issue by heinrich5991** [DDRace/teeworlds#115]
<doc-oc>
sv_emotional_tees 1 allows eyes of tee to change when choose shift and emote. 0 makes off. But player can still type /emote emotename time
 Or bind
 So it is never really off. Please fix so sv_emotional_tees 0 means no eyeemote

**Comment by GreYFoX** [comment]
the time it took u to write this could have been the time u fixed it in

**Comment by heinrich5991** [comment]
I just copied it from Oy's issues.
(where somebody else accidently opened it)
