### ISSUE TITLE
Checkpoints are not stored

### ISSUE THREAD

**Issue by senyai** [DDRace/teeworlds#122]
Hi!
`dtb` files always have '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0' as checkpoints.

**Comment by laxa** [comment]
Cause your map corresponding to these records don't have check entitie ?!

**Comment by senyai** [comment]
Of course it has.

**Comment by laxa** [comment]
Ok so :
- Version of DDRace server you are using ?
- Upload the map where you have this thing.

**Comment by laxa** [comment]
No answer, as far as I know and I tested, check entitie are working correctly.

**Comment by senyai** [comment]
Under some circumstances the bug is happen. I suspect incorrect converting of my `dtd` files from 0.5 to 0.6. Will check it as soon as I have time.

**Comment by senyai** [comment]
After server is running for a long time (about month) I have all zeros.
