### ISSUE TITLE
Timer problemms

### ISSUE THREAD

**Issue by sMo0g** [DDRace/teeworlds#123]
In 0.6.1 One timer - after start. And animation can't run before you started. It's a big problem on my map, and a lot other maps.
And i saw that animation lagg because timer without milliseconds. In 0.6.1 no milliseconds. I think it's should be fixed.

**Comment by laxa** [comment]
We don't need that on ddrace, it's just a mis conception from you if your maps do this.

**Comment by GreYFoX** [comment]
make a poll on the forum, either we will have a timer on the broadcast and make the top timer the server tick timer 
or everything stays as is

**Comment by sMo0g** [comment]
site isn't working :D

**Comment by sMo0g** [comment]
Laxa, a lot maps have background with animation or something else. And this is working after start.. it's annoying a little bit and i think that better if animations things would work before start and without lags.

**Comment by sMo0g** [comment]
Please, can someone do that i need?I just can't register account on ddrace.info to make a poll. So who can do it, just do it and give changed source code files. Please!

**Comment by GreYFoX** [comment]
why can't u register ?, also don't u already have an account ?

**Comment by btd** [comment]
I block him on old site. In im i can explain why.

**Comment by GreYFoX** [comment]
@btd: why ?
