### ISSUE TITLE
force pause/vote player to spectate doesn't work

### ISSUE THREAD

**Issue by alandball** [DDRace/teeworlds#124]
Using the latest sources, if admin uses force_pause on player, it doesn't work. Same for if player votes another player to spectator

**Comment by AdVetter** [comment]
for me voting a player to pause/spectator works, but the "Force vote" button in the "Move player to spectator"-list sets the player to spectator mode, but no pause info is saved.
(force_pause is not working too)

**Comment by senyai** [comment]
I can't force pause for more then zero seconds, seems like sv_vote_pause_time does nothing as I always see
"has been force-paused for 0 seconds" Checked-out just now.

**Comment by ravomavain** [comment]
senyai: are you using DDRace_testing branch?

**Comment by senyai** [comment]
DDRace brach. I see commit 27c1a829 fixes it. Sorry to disturb you.

**Comment by ravomavain** [comment]
this commit is only on DDRace_testing branch, if you have some time to test it that would be nice ;-)
