### ISSUE TITLE
DDRace_testing see and hear others in /pause

### ISSUE THREAD

**Issue by senyai** [DDRace/teeworlds#127]
Hi.

1)    I'm using DDRace_testing at public server and players dislike that they cannot see others when in /pause by default. I know, they can say `/showothers`, but I'm sure this command is used to always show others. So, previous behavior was fine.

2) You cannot hear others in other team when in /pause.

I know, it is a bad practice to describe several issues in one ticket, but please bear with me.

**Comment by sMo0g** [comment]
Yes, it's very annoying, that you can't see players in teams -.-

**Comment by GreYFoX** [comment]
i don't know what is the testing branch is for, i forgot :D

**Comment by GreYFoX** [comment]
@ravomavain and @heinrich5991 what's that branch i don't remember putting it there, did you guys put it ?, if you did then you shouldn't push directly to my repo, instead make a pull request!

**Comment by ravomavain** [comment]
@GreYFoX: it's me who pushed it, you already told me it was a bad thing but i still didn't deleted it, sry. You can remove it if you want (i can't do it right now)

**Comment by senyai** [comment]
@GreYFoX ,btw check that branch out it has a nice pause feature - you can pause anytime. Lots of people at my server liked it. It would be cool if someone make this kind of pause as option, like /forcepause

**Comment by ravomavain** [comment]
@senyai this feature is already planed but nobody have time to test it and fix last bugs :-/ I'll maybe work on it before the end of the year if I have some spare time ;-)

**Comment by GreYFoX** [comment]
@ravomavain : sorry i forget easily and i will not delete it, keep it, maybe someone will work on it and pull req. me

**Comment by GreYFoX** [comment]
@ravomavain what are the bugs currently in there, maybe we need to list them so i can know if i can fix them all when i get a free 30 mins or so

**Comment by ravomavain** [comment]
@GreYFoX iirc this is the only bug i remember but i've not tested it that much. To fix it i suggest to make one of /spec or /pause (the one who remove your tee from the game don't remember which one) behave as current pause, aka make other players visible and hearable

We should also check if there is merge issue with new code but that should be fine

**Comment by ravomavain** [comment]
@senyai : are you sure about 2) ? if players use normal chat you should hear them in all other teams, if they use team chat, there is no reasons to hear them if you are not in their team (i think).

**Comment by senyai** [comment]
@ravomavain I mean no weapon sounds
