### ISSUE TITLE
Server has many memory leaks

### ISSUE THREAD

**Issue by FeoOne** [DDRace/teeworlds#128]
This is a big problem for servers with a small amount of RAM.
The memory occupied by the process DDrace-server increases in arithmetic progression.
According to my observation represents an increase of 10 mb per day.

**Comment by AdVetter** [comment]
I can not reproduce this issue.
My two DDRace servers are now running for 2 weeks.
One with 10mb ram usage and the other one with 7.3mb ram usage.

<b>Edit:</b> On which os?

**Comment by FeoOne** [comment]
What version of server u use?
I'm observed this problem on 1.095a version.

**Comment by AdVetter** [comment]
I'm using a modified DDRace version, running on linux.

<b>Edit:</b>    based on latest DDRace sources.
<b>Edit2:</b> it's v1.096a

**Comment by FeoOne** [comment]
http://img706.imageshack.us/img706/8673/screenshot20111123at233.png
Within a few days lay out one more screenshot.

**Comment by AdVetter** [comment]
OK now your server need as much memory as my server.
Lets see how it develops.

**Comment by GreYFoX** [comment]
Any more feedback ?

**Comment by GreYFoX** [comment]
oops!

**Comment by GreYFoX** [comment]
@FeoOne feedback ? @XXLTomate Feedback!

**Comment by AdVetter** [comment]
@GreYFoX nothing new from my side, my server is always between ~7 and ~12mb ram

**Comment by GreYFoX** [comment]
Then i deem this issue INVALID.
