### ISSUE TITLE
Client side scroll broken

### ISSUE THREAD

**Issue by nicolajkl** [DDRace/teeworlds#153]
Says it all.. The scroll in menu's and stuff is extremely weird.

**Comment by laxa** [comment]
Got this problem too, can't use the wheel of the mouse to scroll :(.

**Comment by Learath2** [comment]
Not a DDRace issue teeworlds/teeworlds#913

**Comment by ghost** [comment]
https://github.com/teeworlds/teeworlds/commit/8372849cbafb02a58fcf8aa7c706cad5c5f16731

current workaround, which works for most of the stuff
(current GUI is not really build well for the current asyncrender implementation)
