### ISSUE TITLE
"Plus double" tile

### ISSUE THREAD

**Issue by sMo0g** [DDRace/teeworlds#155]
What about to do tile which gives to tee a dj? If he already used it.. I think we'll could do nice parts with this thing.

**Comment by eeeee** [comment]
What about to do hooker bot which gives to tee a bj?
// next time please write "double jump" instead of "dj", it takes so long to figure

**Comment by alandball** [comment]
If this feature to be implemented, the code already exists in XXLDDRace, just to let you know so you dont waste time redoing it.

**Comment by Learath2** [comment]
@GreYFoX what do you think about this. Couldn't decide if I should close it.

**Comment by Shereef** [comment]
why not use a stopper top tile ?
the tile that stops tees from falling
like in angry 2 i think

there is this part where you need to hold space and it will get you to climb up and you have to go right then left to go through the stopper so it restores your jump

**Comment by Learath2** [comment]
Viable alternative that can be used to completely mimic this just a bit less flexibility don't think we will add this.
