### ISSUE TITLE
super doesnt work even if sv_test_cmds 1

### ISSUE THREAD

**Issue by alandball** [DDRace/teeworlds#159]
Cannot test maps or go through them using super as tee still freezes

**Comment by heinrich5991** [comment]
It's `sv_test_cmds`.

**Comment by alandball** [comment]
Thats not the point o.O. I use tab to get correct setting. I even say it on its own and server replies with what its value is. I will test it if I start up server with tests cmds 1.

I'm noobie... not even going to say what I forgot to disable.
