### ISSUE TITLE
nickname has left the game (upgrade your client to n-client)

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#165]
in my opinion no client should be able to send server messages

please do something about it

**Comment by alandball** [comment]
When someone disconnects it says player has left the game(no reason given).
If the client sends a reason then it will put that reason in.. Maybe remove the whole thing for reason if its a normal disconnect?

And if its a timeout, then give the reason?

**Comment by Tsin** [comment]
timeouts are a normal server info and that must be =D

**Comment by Learath2** [comment]
teeworlds/teeworlds#950 Fixed :)

**Comment by Tsin** [comment]
yeah fixed closing :D
