### ISSUE TITLE
rework pause

### ISSUE THREAD

**Issue by 3da** [DDRace/teeworlds#166]
using /pause command should not destroy character from the game. Character should stay in the game. So /pause will not be cheat!  :)

**Comment by GreYFoX** [comment]
I recommend you jn DDRacemaX server and trying /pause.
@ravomavain And @heinrich5991 Created a command /spec which takes over when /pause is disabled (which is the case of ddmax), you automatically spectate without killing your character, which does not make it a cheat.

Thanks for your efforts in creating DDRace 3da, and currently I find my self very busy if you want to take over once again please feel free.

**Comment by heinrich5991** [comment]
hey 3da, long time since you last showed up :) welcome back

**Comment by Learath2** [comment]
Wow its really you never seen you before. Started thinking that you weren't real :)

**Comment by alandball** [comment]
Add an option to be able to see players in other teams or not, please?

Edit: for example, will help in tournament/league so players cant see other teams what they doing, especially if the team is stuck on an unseen map, they must figure out themselves and not just copy.

Edit: heinrich, ok.

**Comment by heinrich5991** [comment]
open a new issue please
