### ISSUE TITLE
fast download system by eeeee

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#172]
2 weeks ago eeeee tried to do something with the slow download system 

we had an idea to first test it on ddmax but now as i see it works fine on eeeee's blocker server

theres no point of special test and i think it might go to the main ddrace 

to make it clear this is a very must needed feature 

from a good server i download 14mb map in 1 minute =P
now the sytem allowes to download 1mb in about 3-7 seconds ^^

please someone add it 
https://github.com/eeeee/teeworlds/commit/1cab28f3e17e0a014d3bf56460f955ca7b62a7c7

**Comment by ravomavain** [comment]
Awesome :-) if it work fine we should also add it to vanilla ;-)

**Comment by Tsin** [comment]
yeah there was a little problem 

it works fine for 99.9 % people 

we noted 1 person that had pathetic download on (i think it was) ddrace client then he changed to vanilla client and he had a very very nice download he also download 1 mb map in few seconds

so if thats true

then there would be some clients (maybe some old versions) that still might have the problem
but it was tested on 0.6 and 0.6.1 pure WINDOWS vanilla client by me and in both cases it worked fine (1mb map 3 seconds) also i tested it on ddrace 0.96a client and then i had 14mb in 1 minute

**Comment by GreYFoX** [comment]
Wasn't this added to 0.7 ? If yes then this is done

**Comment by Learath2** [comment]
You mean vanilla 0.7 no I don't remember this being pulled in vanilla.

**Comment by Tsin** [comment]
i think greyfox is talking about new download system that was in plans for 0.7 (from what i heard it might be added in 0.8) 
and not about this exacly "patch" by eeeee

**Comment by Learath2** [comment]
Either way @GreYFoX not added yet
