### ISSUE TITLE
kick vote requires 5 players

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#177]
very nice feature ive seen it on xllddrace server

**Comment by GreYFoX** [comment]
@XXLTomate Pull request ?

**Comment by AdVetter** [comment]
I can't remember that I've added such a feature, but I can make a pull request anyway when I have time.

**Comment by AdVetter** [comment]
This feature was already added to vanilla 0640acb27e9ffb756439aec07b6b07c8ec314c01

**Comment by Tsin** [comment]
yep sv_vote_kick_min  works fine thank you for checking
