### ISSUE TITLE
ddrace organization ?

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#178]
i know it might sound funny but think of it

we need a new code maintainers couse i see that GreyFox dont have time  =/ 

we see lots of ddrace mod forks showing up in 0.6 so i was thinking

why not make a group of ddrace devs that would kept an eye on the mod 

so all this xllddrace i ddrace whatever its called devs would have better access to the main branch would gain help from other devs to their forks and main branch of ddrace might have bugs and other issues fixed/solved

now someone will ask and what if this other devs would like to add some crap features

thats why there would be an organization so they might make a simple vote for this kind uf stuff

why an isse and not ddrace forums topic 
- forums are dead nobody would give a fuck to reply to it

**Comment by GreYFoX** [comment]
There is already an organization named @DDRace and i created it some time ago, this is planned but at the moment i thin kthat all others devs on other ddrace mods are equally busy and most of the may not know how to merge oy
and if someone wants to help git allows them to help, so for now nothing should be changed

**Comment by Learath2** [comment]
Done i guess :)
