### ISSUE TITLE
red hook lasers load after kill

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#181]
very strange bug you can check it on ddmax classic  map skynet 9

when you load the map you have no lasers to drag you

then one tee just need to kill and lasers appear and work

ddrace 1.12a

before kill
http://img6.imagebanana.com/img/v9fuvvf3/before.png

after kill
http://img6.imagebanana.com/img/briy8gus/after.png

**Comment by Tsin** [comment]
big thx to "cat" 

https://github.com/aelio/teeworlds/commit/8bf3e0a2653b25ce0b361b12538d54aac45962a0

Learath2 please take care of it ^^

**Comment by Shereef** [comment]
finally the comments are removed, git amend ftw, i was so rusty i forgot to --all :D

**Comment by aelio** [comment]
Hi there. The nature of issue is that tee's team is unknown untill tees death (thus team 0 is empty and dragger isnt activated), so i moved team reset code to DDRaceInit. Not sure if it wont arise some issues, when, for example, one team member gets disconnected. Maybe we have to keep that removed line, dunno ^^.

**Comment by Tsin** [comment]
"cat" as you already touch the teams and lasers maybe you would be interested in issue 190 ^^

https://github.com/DDRace/teeworlds/issues/190

**Comment by aelio** [comment]
It would be great if someone provide little test map for this case :3
  ----- Original Message -----

**Comment by Tsin** [comment]
you want a test map sure not a problem i will upload here changed version of "Lime" from ddmax so it will be easy to test ^^
