### ISSUE TITLE
ban range bug (bans out of range) 

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#183]
this is ofcourse vanilla bug and its fixed

https://github.com/teeworlds/teeworlds/pull/946

but we dont have it in ddrace fixed so maybe someone could merge it ^^

**Comment by Tsin** [comment]
cmon guys add it rly its very needed =/

**Comment by Learath2** [comment]
Fixed but oh well i can't close it :)  0d7c19889bcf2ce085c57aa681fa8021c8e9f152 & c7f8697c51181db257a865c8e7113fd6b706f22d

**Comment by Tsin** [comment]
thank you fixed closed ;]
