### ISSUE TITLE
admin in status (fixed in 0.7)

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#185]
please add something to status in rcon  couse now you cant know who is "authed as admin and who not"

**Comment by Learath2** [comment]
Will try to do it...

**Comment by heinrich5991** [comment]
maybe do this for vanilla instead

**Comment by alandball** [comment]
It used to have in 0.5.2, the level of the player

**Comment by Learath2** [comment]
Added it teeworlds/teeworlds#985.

**Comment by Tsin** [comment]
oy added it to code =) so i dont know if i should close the issue or wait till we have it merged in ddrace 
https://github.com/teeworlds/teeworlds/commit/78e18dc2cb4f5c537c212c8ff2a6ccc9e2f31981

**Comment by Learath2** [comment]
Tsin won't merge on github most prolly just yet.
