### ISSUE TITLE
Drag slowdown effect

### ISSUE THREAD

**Issue by ghost** [DDRace/teeworlds#194]
You guys may or may not be aware of this affect when dragging another tee, but what happens is that the first time a tee is dragged along the ground he starts off at a certain speed but then the speed he can be dragged by slows down, almost as if there is an increase in friction. This continues to he gets to a constant speed which is noticeably slower than the initial speed. The only way to get back to that initial faster drag speed, is for the tee to pause (killing his character) then unpause. 

I recommend that you keep the slowdown pull effect, but instead of having to repause to reset it to its initial speed, have it so that once the tee has come to a complete stop it resets it automatically.

**Comment by Tsin** [comment]
nothing new was in 0.5.X everyone knows about it

https://github.com/teeworlds/teeworlds/issues/541

this issue can be closed its tw bug and not ddrace but thank you ZodiacZA for info ^^

**Comment by ghost** [comment]
Oh sorry, thought it had more to do with DDrace than Teeworlds as you don't really go around dragging people in Teeworlds :P But maybe it should remain a DDrace issue because it doesn't seem like it is a high priority on there list as it has been around for 2 years and they still haven't gotten around to fixing it. Whereas for DDrace it is quite a big issue that needs to be dealt with, especially if you guys plan on removing pause (which I recommend)

**Comment by Tsin** [comment]
no it must be closed because like i said its not ddrace issue and "we" cant rly fix it it must also be fixed on "clients" and ddrace is only server side mod 

and about that statement : 
"it doesn't seem like it is a high priority" it is hight priority couse its in 0.7 milestone without that bug fixed 0.7 wont be released so close the issue ^^

**Comment by ghost** [comment]
I see, didn't realize that :)
