### ISSUE TITLE
/rank nick - spam 

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#197]
for example

/rank Tsin

then peole see Tsin finished map in TIME then dont see who wrote that /rank 

only the person that made that rank see for example if i make /rank Tsin
then i will see
Tsin finished map in time .... (by Tsin)

/rank should always show to all people on server who used that command then it will be easier to ban a spammer

**Comment by Shereef** [comment]
for the record 7f7a46b497427d8f5cc13c8f731512a2951b4778 is also related

**Comment by Shereef** [comment]
@Tsin Please test the sql version
@Learath2 Please test the normal version

Thanks guys

**Comment by Learath2** [comment]
@GreYFoX tested it the others don't even get the message probably true for SQL version too

**Comment by Shereef** [comment]
What happened exactly ?

how many clients did you test with?
what is the message you saw
which client saw it ?

**Comment by Learath2** [comment]
@GreYFoX I saw the proper message with requested by Learath2 but the other client didn't get the message. I tested it with @heinrich5991 he only what he requested and I only saw what I requested.

**Comment by Shereef** [comment]
do you have sv_hide_scores 1 ?

**Comment by Learath2** [comment]
Nope

**Comment by Tsin** [comment]
hmm why we wont just take it from "teerace" it works there nicely

**Comment by Shereef** [comment]
We don't need to the fix is very easy, Someone just needs to remind me when
i have free time that i should fix stuff, I Usually just go and play and i
forget there are stuff to fix :/
@Tsin usually i'm on teeworlds thursday night, remind me that i fix stuff,
prolly iwill on thursday night or friday morning
