### ISSUE TITLE
1.15a rly needed

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#198]
i think its time to make a good decission of releasing a good 0.6.1 final and working client or remove 1.14a from download website and keep up with 1.096a 

the reasons why 1.14a and 1.12 should be removed 
-scroll bug 
bugged entities specialy TELE entites
-they dont have check and red teleport
-there might be more bugs but i dont know i use 1.096a and i tell all mappers to do it  (it works and dont have very annoying entites rly the new entities SUCK im talking about graphics, never change something that works good) 

so there are 2 solutions remove 1.14a and 1.12 from download (ddrace.info) 
1. keep a good and working 1.096a and just add a special binary for server with newest code
2. make a new 1.15a release and add a fix for scroll bug also add a good entities that are similar to the ones from 1.096a

btw 1.096a have a strange bug about "show players in other teams" it only works when you are logged in as admin oO dont know if it was changed in 1.1X

and ofcourse if you will make 1.15x then please someone also make an official windows build (with console people do use it dont know why linux builds dont have it, also little question about linux builds why there is no icon file ? maybe make an icon file in .png format all linux distros with LAUNCHER will use it then but about this should say someone that is an linux "expert" =P)

**Comment by Learath2** [comment]
No one is going to bother backporting everything. 1.14 should be fixed. @GreYFoX @heinrich5991 what are we going to do about 0.7

**Comment by Tsin** [comment]
im not talking about backporting EVERYTHING im not a mad man :P 

im only talking about fixing 2 most important things

scroll bug and teleport entities (and making windows build) and keep it as official last 0.6.1 version and dont give a fuck about 0.6.X and only make 0.7

or remove 1.14a and keep 1.096a as main client and just add new server binary

**Comment by heinrich5991** [comment]
I'd propose a mod rewrite for 0.7. Huge task, not all things would be supported from start on.

**Comment by Tsin** [comment]
guys no no you dont get it you talk about HUGE TASKS and im just talking about small release to get rid of faily 1.12 and 1.14 couse they rly shouldnt be in download on ddrace.info
