### ISSUE TITLE
2 bugs in fast download (system/hack)

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#202]
ONE : critical crash server bug how to :

[03:31:43] <laxa> make a files eg : spam.txt
[03:31:53] <laxa> put thousands of "say spam"
[03:32:09] <laxa> bind it to some key or just f1 and write "exec spam.txt"
[03:32:15] <laxa> then server crashed

TWO :  when a player joins the server and map downloads and then he cancle the download without joining in or that person will have out of buffer

then in server status we have ID X unknown type 0

**Comment by noother** [comment]
howto: connect, spam around, get dropped, reconnect => crash
[12-12-23 04:32:37][assert]: src/game/server/player.cpp(16): already used

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000426d21 in dbg_assert_imp ()
(gdb) bt
#0  0x0000000000426d21 in dbg_assert_imp ()
#1  0x000000000044ffaf in CPlayer::operator new(unsigned long, int) ()
#2  0x000000000044a55b in CGameContext::OnClientConnected(int) ()
#3  0x000000000042bfa3 in CServer::ProcessClientPacket(CNetChunk*) ()
#4  0x000000000042c984 in CServer::PumpNetwork() ()
#5  0x000000000042d411 in CServer::Run() ()
#6  0x000000000042d84f in main ()
```

cae8c68d8782dfd31017c12915065a68c72729cc is the first bad commit
commit cae8c68d8782dfd31017c12915065a68c72729cc
Author: eeeee eeeee@qwe123.info
Date:   Sat Apr 14 01:30:18 2012 +0200

send ahead window for maps downloading. works with vanilla client.

**Comment by Tsin** [comment]
both issues here might be fixed

will close after some tests on ddmax ^^

**Comment by Tsin** [comment]
looks like everything works fine 

fixed by https://github.com/DDRace/teeworlds/commit/ee2647de4191066453b11862895cb32d4b729427 and https://github.com/DDRace/teeworlds/commit/02036bc876c03f9ac23b9b5c5060db0bbdac4c2e

**Comment by Shereef** [comment]
great work @eeeee and thanks @tsin for testing
