### ISSUE TITLE
team bug remains

### ISSUE THREAD

**Issue by heinrich5991** [DDRace/teeworlds#206]
Virus2K reports on DDRaceMax that if you join a team and disconnect, it's blocked afterwards.

**Comment by Learath2** [comment]
Can confirm on my own build of last commit.

**Comment by Tsin** [comment]
yes thats true (i forgot to open an issue also there is a strange bug with records a player gets info that he finished the map but records arent saved so you wont see them in /top5) 

btw. ^^ what is DDRaceMax i know a server DDracemaX but not what heinrich wrote =P

**Comment by Shereef** [comment]
Is it back or is it not ?

**Comment by Tsin** [comment]
fixed sorry for problems dont reopen
