### ISSUE TITLE
lags with 2 clients (1.15a) on 1 pc

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#213]
so 

if i open on my pc 2 clients (1.096a) everything works fine ping is normal (my pc isnt rly that bad so it can handle even 8 clients without any problems - games are in windowed mode both 1920x1080 high details)

game works fine smooth no problems at all 

if i open 1 client (1.15a) and 1 client (1.096a) ping jumps a little bit fps gets a little lower but i can somehow play but it lags a lot ping jumps from 20 to 70

but if i open 2 clients 1.15a game lags like hell ping jumps to 200 or even more pc barely handels them

all this was tested on ddracemax and on my lan server (map dm1) with the same resault 

please someone try to confirm it i dont know if its ddrace client or tw bug

**Comment by Tsin** [comment]
found the blame 

gfx_threaded 1

if you change to 0 and restart the client it works good

so i if old system with gfx_threaded 0 worked fine for everyone then maybe we should stick with it for now as a default

**Comment by Shereef** [comment]
Won't fix(Oy style :D). submit to teeworlds repo.

**Comment by Tsin** [comment]
omg you noobzor i hate you zor  so much zor i dont talk about fixing it :P im talking about making it 

gfx_threaded 0  as a default so then nobody will complain on new ddrace client (in 0.6.1 stable there is no gfx_threaded 1 so nobody complains about this kind of problems and nobody have normal access to 0.7 trunk to know about this "problem")

**Comment by Shereef** [comment]
Agreed that i am a noobzor but still won't fix :p

just joking ok will do later (at work now)

**Comment by ghost** [comment]
tried it on my pc, cant find much differences :/
gfx_threaded 1: lags with 3 clients
gfx_threaded 0 / 0.6.1 client: lags with 3-4 clients

**Comment by Tsin** [comment]
so what i observed

on windows stable 0.6.1 client
1 client about 300 fps smooth 
2 clients both about 130 fps smooth

on windows new 1.15a client
gfx_threaded 0
works the same like above  only maybe 5 fps less
gfx_threaded 1 
1 client works nice but about 280 fps
2 clients game lags like hell pings jump to 130 

now linux stable 0.6.1 client
1 client about 310 fps smooth 
2 clients both about 140 fps smooth
aka the same like on windows but kind of feel smoother

on linux new 1.15a client
gfx_threaded 0
1 client smooth 290 fps 
2 clients smooth 130 fps
gfx_threaded 1
1 client 280 fps sometimes lags but very very little 
2 clients 115 fps game lags ping stays normal and dont rly reacts that much strange like on windows 

so final conclusion 
old client on linux works better like on windows
new client on linux with gfx_threaded 0 or 1 
works worse like on windows but dont have that huge ping jumping

later when i will have more time i will make a new issue on tw repo about all of this

but still we have 2 choices
1. remove gfx_threaded 1 from ddrace client and keep only the old "engine" code
2. keep new engine but make gfx_threaded 0 as a default (maybe add a special ON/OFF feature in DDRace tab in game client next to cheats show ghost  etc etc)

**Comment by Tsin** [comment]
next reason why we cant use gfx_threaded 1 
http://www.youtube.com/watch?v=pAq4fh5RKsk&feature

**Comment by Learath2** [comment]
Because a video is private ?

**Comment by Shereef** [comment]
Yes @Learath2 because of threading the video becomes unsafe fro threading,
Google Thread Safety!

**Comment by Shereef** [comment]
it's a joke :D

**Comment by Learath2** [comment]
You no say ? :smile:

**Comment by heinrich5991** [comment]
is this a chatroom? ^^

**Comment by Tsin** [comment]
omg what an idiot came to me gave me video i asked him to make gfx_threaded 0 he said that now it works fine and he removed the video gone off from skype

**Comment by Learath2** [comment]
@Tsin meh.
@heinrich5991 why not we can use it as one ^^

**Comment by Tsin** [comment]
chatting in comments is so AWESOME 

btw animation in 1.15a acts strange when you stand on start line :D

**Comment by Tsin** [comment]
http://www.youtube.com/watch?feature=player_embedded&v=pAq4fh5RKsk

**Comment by Learath2** [comment]
EWWWWW that vid looks sick

**Comment by Learath2** [comment]
@Tsin it should be fine with this, commit closed it if you want you can open it again ^^
