### ISSUE TITLE
noother's afk

### ISSUE THREAD

**Issue by Tsin** [DDRace/teeworlds#27]
please check the implementation of noother's afk

**Comment by GreYFoX** [comment]
i've been waiting for you in irc to tell you this doesn't mean anything to me
you haven't told me hwat is wrong or what to look for
do snakes come out and bite who ever is afk ?
do virgins refuse to touch you ?
you have to be specific or i just won't know what to fix

**Comment by Tsin** [comment]
i dont know anything about snakes but virgins just love to touch my ..... 

about the issue it should work like this
-you set the time  of afk
-when 50% of that time ends you get a message "you are afk for blah blah" 
-after 90% of time passes you get a second message
-100%  you get kicked
-only mouse move can reset the afk timer
-using keyboard wont do anything

**Comment by GreYFoX** [comment]
thanks will  be fixed soon
