### ISSUE TITLE
Rework Teams

### ISSUE THREAD

**Issue by GreYFoX** [DDRace/teeworlds#30]
@heinrich5991 is currently reworking teams

**Comment by btd** [comment]
What is a current state of this issue?

**Comment by GreYFoX** [comment]
No one is working on it but I'd recommends asking @heinrich5991 if u wanna do it, to see what he reached, but at the current state I think teams system is fine for now

**Comment by GreYFoX** [comment]
I forgot the objectives of this issue and why it was necessary and no one is working on it so i am closing it!
