### ISSUE TITLE
White tile by tele and speedup!

### ISSUE THREAD

**Issue by Xystus** [DDRace/teeworlds#38]
If i made a map with DDrace Client. And put a teleporter in it, and save the map. And wanna try it, i got a white block on the place from the teleporter of speedup.

I don't know if this is a bug or not. But is very annoying ;)

**Comment by ravomavain** [comment]
Can't reproduce on a new map, but if I edit an old one I got the same problem :/

Edit : and on the old map, adding a new teleporter fixed the problem.

**Comment by Xystus** [comment]
Sow what can i do for a new map to get that away??

**Comment by GreYFoX** [comment]
1. go to http://bit.ly/DDRace
2. download the latest DDRace
3. open the client and the editor
4. load the map that causes this
5. save it
6. host it
7. have fun.
