### ISSUE TITLE
pause bug

### ISSUE THREAD

**Issue by Cristall** [DDRace/teeworlds#45]
its a bug if you use pause and spec
1. start and use /pause anywhere
2. esc and go out of spec and start
3. go into spec and use /pause again
   you are at the position of the first pause and you cant pause between 2 and 3

i think you should not go out of spec while pause.. there is a messsage but it work

**Comment by ravomavain** [comment]
Noticed it too, I think that the right way to fix that is to unpause player (like if he use /pause again), when he try to join the game, so we can't accidentally lost our current paused data.

An other nice feature will be to replace the classic "join the spectators" and "join the game" message by a pause message, so new players will know how to use it (and will not join spectators normally thinking they game will be restored when they come back).

**Comment by ravomavain** [comment]
I found where is the problem : there is a missing "else" between line 1000 and 1001 of src/game/server/gamecontext.cpp (it may have been lost in the big update to 0.6)

**Comment by GreYFoX** [comment]
sorry i just fixed it without looking because i already knew about this, was just enjoying having a char saved in game, some times i would play and finish then spectate and unpause and play with the other char xD
anyway it's fixed now
