### ISSUE TITLE
Records not saving for maps in subfolders

### ISSUE THREAD

**Issue by alandball** [DDRace/teeworlds#49]
I have tested this and found that the reason my server couldnt read or make records, is because the maps are in subfolders.
An example: skynet1: located in data\maps\1\
server config: add_vote "Skynet 1" sv_map 1\skynet1

It works well,and when someone finishes the map, it shows their time, until map changes. I look in records folder in base teeworlds folder, and no record

Also, if i add the skynet 1 record file from the server that was made pre-0.6, it also doesnt read it when the map is in that sub folder. It all works fine if maps are not in subfolder

**Comment by GreYFoX** [comment]
I'll check it out, but tell me why is it significant to have maps in sub folders !

**Comment by alandball** [comment]
For ddrace, it is a problem if there are maps in subfolders, as the records then dont record. Maybe what i was getting at was that there is allowed to be maps in subfolders, then the mod should still continue to function the way its meant to. If its easier maybe then disallow the usage of maps in subfolders. I would just guess its good practice to make sure a feature is compatible

I dont mind whether i have my maps grouped in sub folders or not, so it probably isn't necessary, other than compatibility.

**Comment by Learath2** [comment]
Is this a confirmed bug ?

**Comment by AdVetter** [comment]
Fixed ec3c96abd6e82bd96a926e95cd2d51caaeff2869
