### ISSUE TITLE
tune and tune_reset

### ISSUE THREAD

**Issue by alandball** [DDRace/teeworlds#50]
When server admin does tune_reset it seems to load the default teeworlds tunings, rather than the default ddrace tunings. For one: Bullets act weirdly(moves super fast) etc

Also when a map is loaded that holds a cfg(eg koule 7) that has perma hook, when the map is changed, perma hook is still enabled. Please add the tune reset function(like in 0.52 trunk 1.6......) where it tune resets, then loads map config if there is one. If there isnt map will then run with default cfg. To fix, for now I have made a config for EVERY map, incase a map is loaded after koule 7.

**Comment by GreYFoX** [comment]
i host a server has koule 1 to 15 and the hook is rest when changing map from 7 to anyother map

but not because of the ture_reset only command, i will fix it so that tune_reset resets DDRace tunes as well as tw tunes
thanks for the report

**Comment by alandball** [comment]
Sure, but im still not sure why the hook stays permanent. Im using 1.075a uploaded on 26 april trunk from the ddrace.info site. I will test with the now 1.076a

**Comment by alandball** [comment]
Also. it is not just the manual tunes in the config that arent changed back, but optional tiles that change settings and tunes when a map is loaded with such tiles, and when the next map is loaded those changes are still there.

This became apparent to me when someone opened this thread: http://ddrace.info/forum/showthread.php?t=610

**Comment by ravomavain** [comment]
Here is a patch that should fix tune_reset ;-)

**Comment by alandball** [comment]
I just tested the b11 available on ddrace.info. When a map is voted, and the map has a config that changes any settings, those settings are not reverted when a new map is voted/loaded. Those settings only revert if server is restarted. This did not happen on the trunk ddrace that were before 0.6.0. Please test this using the latest download from ddrace.info. It cant just be me with this problem, no other maps have configs. The perma hook for koule 7 is not reverted after map-change. I dont know why your server is different. I will put my config up on ddrace.info.

**Comment by alandball** [comment]
Thanks
