### ISSUE TITLE
Weird Speeder bug

### ISSUE THREAD

**Issue by GreYFoX** [DDRace/teeworlds#51]
When in a speeder with max speed if a tee presses A (left or hook the ground, the tee can go int othe opposing direction of the speeder, can go very fast !!

**Comment by alandball** [comment]
This often happens, but for me, I get stuck if lets say speeder is perfect right, and I hold left, then I get stuck in the position after a while. And no amount of trying can move me, say if other tee hook me or i hook a nearby wall.

Also, what you mentioned happens, and very high speed then can be obtained, it feels almost as if the energy builds up inside tee. Have this go on long enough, and you get stuck, as i mentioned above in the speedup.
