### ISSUE TITLE
admin access to config level commands

### ISSUE THREAD

**Issue by alandball** [DDRace/teeworlds#54]
I have had a problem on my server, where an admin set sv_register to 0, and sv_test_cmds to 1, and was able to 'super'.  The other tee were then dragged to the finish line. Please can the level of access be upped, so its only config? Thank you.

**Comment by GreYFoX** [comment]
if someone cheated then the records file / sql table were never changed

these commands are for testing, if it's so happens that they are activated in a middle of a game the records are not modified.

i will close htis for now, if you are not satisfied please reply here to tell me what you think
