### ISSUE TITLE
bug at score(changing records in top on more bad)

### ISSUE THREAD

**Issue by PenguiN560** [DDRace/teeworlds#55]
Possible to del any records from top for get first place. 

How it work:
For a start we must enter on server with no record nick (have -999 score) after change nick on guy what score we want del from top. On command /rank we get his time and place but also have -999 score and if now we finish map his record will be change to our time(not mater have he more better time or not)

Was found on one of Nut DDrace servers on nut short race 2

**Comment by GreYFoX** [comment]
fixed
