### ISSUE TITLE
pass-system

### ISSUE THREAD

**Issue by Styvi26** [DDRace/teeworlds#62]
Can you make a pass-system?

**Comment by btd** [comment]
What does it mean?

**Comment by ravomavain** [comment]
btb: http://pix.toile-libre.org/upload/original/1311326249.png
I don't realy know what it's about but it's for TeeFoot, not DDRace ;-)

**Comment by Styvi26** [comment]
yes, i mean that for teefoot.
when a player give a pass to another player. and than give it a point for both player.
and it's already possible to make it unhold? the command sv_player_keeptime doesn't work.
thanks. (this is a very nice mod :D)
