### ISSUE TITLE
teefoot

### ISSUE THREAD

**Issue by Styvi26** [DDRace/teeworlds#68]
hey guys

Do you still work at the teefoot mod?

when yes:

important bug 1: the tileset of the redgoal is buggy. it isn't air as the bluegoal. you can test it on the teefoot server.

important bug 2: if a player has the ball and makes suicide, the ball disappears. the same thing happens when a player goes with the ball in a death-tile. sometimes it happens when a player chats and becomes the ball.

suggestion 1: activate sudden-death
suggestion 2: if a player makes a goal,  that it makes a broadcast with the name
suggestion 3: if a player gives a pass, that he becomes a point too.

It would be really nice if you could change these matters.

regards styvi26 (i host the teefoot-servers since a month)

**Comment by GreYFoX** [comment]
I'm rebuilding teefoot from scratch ETA 15 days
