### ISSUE TITLE
bind doesn't work with more than 1 command

### ISSUE THREAD

**Issue by noother** [DDRace/teeworlds#70]
Example: bind lalt "emote 7; kill; +fire". < Only emote 7 gets executed.
It used to work in all previous versions.
This bug doesn't exist in latest vanilla.

**Comment by theandi103** [comment]
You have a space after the comma. You have to wirte like this
bind lalt "emote 7;kill;+fire"

**Comment by noother** [comment]
What can I say - No, that's nonsense. Either with or without space should work, but it doesn't.

**Comment by JulianAssange** [comment]
i just did it and it works fine... ( space and no space)

**Comment by noother** [comment]
No, it doesn't.
Did you test with the latest code? (44b636d37f103b6b10c4)

**Comment by JulianAssange** [comment]
Yep my bad, It seems that the newest code has many bugs. hopfully greyfox has time :)
