### ISSUE TITLE
RCON causes Broken pipe

### ISSUE THREAD

**Issue by senyai** [DDRace/teeworlds#71]
Tried minimal code for rcon connecting:

``````
import telnetlib
HOST = "::1"
PASSWORD = "TEST"
tn = telnetlib.Telnet(HOST, 8406)
tn.read_until("Enter password:")
tn.write(PASSWORD + "\n")
tn.write("say TELNET TEST\n")
tn.close()
print tn.read_all()```

and ddrace server stopped. I could not use twisted becouse server opens only ipv6 port. Thx.
``````

**Comment by heinrich5991** [comment]
why don't you use a pure tcp connection?

**Comment by senyai** [comment]
This issue is not about using telnet sessions, it is about security.

**Comment by heinrich5991** [comment]
Sure, but I suggested you to use a pure tcp connection.
You seem to have accidently clicked the "Comment & Close" button, could you or @GreYFoX please reopen this ticket?

**Comment by GreYFoX** [comment]
Is this still present ?

**Comment by senyai** [comment]
I'd check it out, but I can't compile the latest version:

```
senyai@ubuntu:~/ddrace_0.6.1/teeworlds$ nice ../../teeworlds_src/bam-0.4.0/bam server_release
other/sdl/sdl.lua:43: attempt to compare number with nil
```

**Comment by heinrich5991** [comment]
`bam config`
fixes this

**Comment by senyai** [comment]
@heinrich5991 thx, compilation is ok now
@GreYFoX, yes bug is still there

**Comment by GreYFoX** [comment]
@senyai please write the steps you used to test it

**Comment by senyai** [comment]
@GreYFoX  My first post has the code - that's it. I use python 2.6.
I noticed my config file has \r\n endings, all the RCON related lines I have are:

```
ec_port 8406
ec_password TEST
ec_bindaddr 127.0.0.1
```

**Comment by GreYFoX** [comment]
E:\Users\shereef\Desktop>econ.py

E:\Users\shereef\Desktop>econ.py

[11-12-27 17:18:27][econ]: client accepted. cid=0 addr=127.0.0.1:56313'
[11-12-27 17:18:27][econ]: cid=0 authed
[11-12-27 17:18:27][econ]: client dropped. cid=0 addr=127.0.0.1:56313 reason='failed to send packet'
[11-12-27 17:18:40][econ]: client accepted. cid=0 addr=127.0.0.1:56319'
[11-12-27 17:18:40][econ]: cid=0 authed
[11-12-27 17:18:40][econ]: client dropped. cid=0 addr=127.0.0.1:56319 reason='failed to send packet'

**Comment by GreYFoX** [comment]
I don't have ipv6 yet on that machine so:

import telnetlib
HOST = "127.0.0.1"
PASSWORD = "TEST"
tn = telnetlib.Telnet(HOST, 8406)
tn.read_until("Enter password:")
tn.write(PASSWORD + "\n")
tn.write("say TELNET TEST\n")
tn.close()
print tn.read_all()

**Comment by GreYFoX** [comment]
Using Telnet

Enter password:
TEST
Authentication successful. External console access granted.
[econ]: cid=0 authed
shutdown
[server]: cid=0 cmd='shutdown'
closing console

Connection to host lost.

Press any key to continue...

**Comment by GreYFoX** [comment]
i'm no python coder but @senyai ....
<code>
import telnetlib
HOST = "127.0.0.1"
PASSWORD = "TEST"
tn = telnetlib.Telnet(HOST, 8406)
tn.read_until("Enter password:")
tn.write(PASSWORD + "\n")
tn.read_until("authed")
tn.write("say TELNET TEST\n")
tn.read_until("TEST\n")
tn.write("shutdown\n")
tn.close()
print tn.read_all()
</code>

use a proper client.
closed...

**Comment by senyai** [comment]
@GreYFoX I have no trouble using proper client. I'm sure this bug is linux specific, and maybe it has nothing to do with DDrace but teeworlds. 

```
Program received signal SIGPIPE, Broken pipe.
0x0012d422 in __kernel_vsyscall ()
(gdb) bt
#0  0x0012d422 in __kernel_vsyscall ()
#1  0x0013b3e8 in send () from /lib/tls/i686/cmov/libpthread.so.0
#2  0x0806fefb in net_tcp_send (sock=..., data=0xbfffe35c, size=23) at src/base/system.c:1219
#3  0x08068dec in CConsoleNetConnection::Send (this=0xb7fe3870, pLine=0xbfffe81c "[econ]: cid=0 authed") at src/engine/shared/network_console_conn.cpp:170
#4  0x08055cbb in CNetConsole::Send (this=0xb7fe2a60, ClientID=0, pLine=0xbfffe81c "[econ]: cid=0 authed") at src/engine/shared/network_console.cpp:154
#5  0x0804e463 in CEcon::Send (this=0xb7fe2a1c, ClientID=-1, pLine=0xbfffe81c "[econ]: cid=0 authed") at src/engine/shared/econ.cpp:160
#6  0x0804dc24 in CEcon::SendLineCB (pLine=0xbfffe81c "[econ]: cid=0 authed", pUserData=0xb7fe2a1c) at src/engine/shared/econ.cpp:42
#7  0x0805a049 in CConsole::Print (this=0x81551e0, Level=0, pFrom=0x80c0139 "econ", pStr=0xbfffec7c "cid=0 authed") at src/engine/shared/console.cpp:227
#8  0x0804e0af in CEcon::Update (this=0xb7fe2a1c) at src/engine/shared/econ.cpp:113
#9  0x080758c4 in CServer::PumpNetwork (this=0xb7ce9008) at src/engine/server/server.cpp:1163
#10 0x0807657f in CServer::Run (this=0xb7ce9008) at src/engine/server/server.cpp:1378
#11 0x08078503 in main (argc=1, argv=0xbffff7c4) at src/engine/server/server.cpp:1833
```

I cannot find out why SIGPIPE happens - pipe is ok when you send 'Enter password:' and 'Authentication successful. External console access granted.' but fails at '"[econ]: cid=0 authed"'. When I added sleeps it worked.

```
import telnetlib
from time import sleep
HOST = "127.0.0.1"
PASSWORD = "metall"
tn = telnetlib.Telnet(HOST, 8307)
sleep(1)
tn.read_until("Enter password:")
sleep(1)
tn.write(PASSWORD + "\n")
sleep(1)
tn.read_until("authed")
sleep(1)
tn.write("say TELNET TEST\n")
sleep(1)
tn.close()
print tn.read_all()
```
