### ISSUE TITLE
0.6.1 : Collision acting weird

### ISSUE THREAD

**Issue by laxa** [DDRace/teeworlds#78]
I experienced some really weird things with collision and HF.

**Comment by GreYFoX** [comment]
were you using an 0.6.1 client on a 0.6.1 server ?

**Comment by laxa** [comment]
Yes.

**Comment by GreYFoX** [comment]
Demo ?

**Comment by laxa** [comment]
Can't find demo of it cause the demo stop after start line...

**Comment by laxa** [comment]
Ok, I finally found what was causing weird collision !
Apparently team feature does not remove collision... Making really really strange things and making the prediction of the client to fail too...

I got 2 demo for this : http://L4x4t0r.free.fr/bug.demo, at the really end of the demo, 51:30, I come to the end of a noobfilter, at the end of the laser door is another tee but in a different team, when the demo stopped, I just went through laser door alone...
Second demo : http://L4x4t0r.free.fr/bug2.demo from 2:30 to something like 4:00, I make some test with mates on different team, you can try yourself, prediction crash, and you can move tee from other team or stand on them...
To watch demo, you need this map : http://L4x4t0r.free.fr/HardcoreZ.map

**Comment by laxa** [comment]
Thanks, it's fixed =).
