### ISSUE TITLE
Client 0.6.0 crash on 0.6.1 server

### ISSUE THREAD

**Issue by laxa** [DDRace/teeworlds#79]
At least on Race server and DDrace server, 0.6.0 trunk client crash on server with 0.6.1 race/DDrace.

**Comment by GreYFoX** [comment]
it's all about the map, 0.6.0 client will NEVER know maps created by 0.6.1 because it doesn't have the new layer and group name ...etc 
not a bug

**Comment by Tsin** [comment]
only DDRace 0.6 clients crash vanilla 0.6 and vanilla 0.6.1 works fine so i think this bug can be fixed (but aslo will be pointless because the fix woukd be then done on 0.6.1 :D)

btw maybe there should be away to let 0.6.1 editor to save maps with new features that kill clients and without

**Comment by GreYFoX** [comment]
don't get it
