### ISSUE TITLE
teefoot: server crash shot+suicide

### ISSUE THREAD

**Issue by Styvi26** [DDRace/teeworlds#80]
bug in teefoot:
- if a player shot and makes suicide at the same time the server crashes.

**Comment by GreYFoX** [comment]
i tried it no crash

1- i got the ball
2- shot it
3- killed
nothing happened

**Comment by Styvi26** [comment]
sry, i tested it again:
you must look at the ground. then shoot and in the same second selfkill ->crash

the same thing is if you shot and go in a death-tile in the same instant.

i tested the server in my 24/7 and he never run for more than 5 hours. i don't know why but i could be because of this bug.
(the version before updating is more stable)

**Comment by GreYFoX** [comment]
It's not a crash it's an infinite loop by bass

**Comment by GreYFoX** [comment]
please submit logs and backtraces if the server is still unstable

**Comment by Shereef** [comment]
@Styvi26 is it still unstable

**Comment by Styvi26** [comment]
i run the server since yesterday night and both server are still running. i dont know how many player are played, but i think, now the server is stable. great ( ;
i will post it when the server crashs.
