### ISSUE TITLE
no /cmdlist. version 1.093a

### ISSUE THREAD

**Issue by senyai** [DDRace/teeworlds#86]
When you say '/info' you see "For more Info /cmdlist", and then you say '/cmdlist' and command does not exists. IMO cmdlist should be deprecated, since all admin commands can be typed in console and info about commands can be placed at one screen. People use /top5 /rank /emote and nothing else as I can see. Am I right?

**Comment by GreYFoX** [comment]
fixed

**Comment by alandball** [comment]
Was /rules added? just for example, clan servers might like this, I for one like this because then ISP ROE(rules of engagement) can be put under /rules, by copy and pasting into the cfg... will check this when i have time and report back here.
