### ISSUE TITLE
map list in ddrace client and server

### ISSUE THREAD

**Issue by Shahan** [DDRace/teeworlds#93]
How about developing admin stuff in client:
Admin of ddrace server, using ddrace client, can look a list of maps (data/maps directory) and chose perfect one to start instead of connecting host for chosing  map and writing in rcon "sv_map"

I don't open this issue at oy's repo because vanilla server don't need this feature. And only ddrace has hundreds of maps.
Predicting question about adding votes:
i hate adding votes in autoexec. It's long and boring.

**Comment by GreYFoX** [comment]
There is already an issue about this in Oy's repo and they intend to do it, map autocompletion
https://github.com/oy/teeworlds/issues/359
