### ISSUE TITLE
New solo entitie : missing broadcast from spec view

### ISSUE THREAD

**Issue by laxa** [DDRace/teeworlds#95]
When you spec someone in a solo zone :
- You can only hear when he double jump. So you can't hear : kill sound/bullet/hammer/hook
- You don't see what's the number of seconds before he unfreeze

**Comment by GreYFoX** [comment]
Does this still apply @Laxa ?

**Comment by laxa** [comment]
Yeah, broadcast is broken after a tee has go through a solo entitie, no way of "fixing" it going through off solo entitie.
Only kill makes broadcast come again.

**Comment by GreYFoX** [comment]
@laxa the broadcast message !! ?!! i think i removed it !

**Comment by laxa** [comment]
I am not talking about broadcast message, but about sounds.

**Comment by GreYFoX** [comment]
It's called sound mask
