### ISSUE TITLE
Spectate

### ISSUE THREAD

**Issue by JulianAssange** [DDRace/teeworlds#98]
if someone is in force-spectate for a limited time, if they leave they get banned for how ever long they have left until they can re-join the game.

**Comment by GreYFoX** [comment]
is that the wanted behaviour or the current behavior ?
u are saying it like a statement not a suggestion, i'm confused

**Comment by ravomavain** [comment]
As far as I'm concerned, this is not the current behavior (force-pause code is here : https://github.com/GreYFoX/teeworlds/compare/0ae0b0bb...3f2dc361).

**Comment by JulianAssange** [comment]
^ if i would have found that, I would have tryed to code it myself..

anyways, it's wanted.. Because currently you can get force spectate, leave the game, then rejoin so u dont have to wait the X ammount of minutes to re-join

pretty much: i want the old mute behavior how you would be banned for how long your mute was if u left, but for the force-pause timer thing.

sorry if i dont explain myself well lol.

**Comment by Learath2** [comment]
well force pause pauses the player doesnt make them go to spectate so if they leave they lose state if they wait they can continue. I think its fair enough :) (i know its an old issue (should be closed ?))

**Comment by GreYFoX** [comment]
i think @Learath2 said what i wanted to say if i understood correctly, you force spectate afk people or bocking people who block in the mid map, you force them to pause or spectate to get rid of them temporarily, if you want them banned just kick them!

the current behavior is what i think is good for it
